ember-a11y/ember-a11y-testing

test-support/helpers/a11y/a11y-error.js, test-support/helpers/a11y/helpers/actions.js, test-support/helpers/a11y/helpers/alt-text.js, test-support/helpers/a11y/helpers/aria-properties.js, test-support/helpers/a11y/helpers/color-contrast.js, test-support/helpers/a11y/helpers/form-labels.js, test-support/helpers/a11y/helpers/id-checks.js, test-support/helpers/a11y/helpers/links.js, test-support/helpers/a11y/helpers/no-read.js, test-support/helpers/a11y/register-a11y-helpers.js
Closes [#2].
When throwing an `A11yError`, include the element separately from the
message.
Then, during `a11yTest` invocation, catch the error, log it to the
console, then rethrow.
Ensure the error [preserves the current frame's stack trace][mozilla].
[#2]: https://github.com/trentmwillis/ember-a11y-testing/issues/2
[mozilla]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#Custom_Error_Types
=> Log `A11yError` element

test-support/helpers/a11y/helpers/form-labels.js, tests/acceptance/form-labels-test.js, tests/dummy/app/templates/form-labels.hbs
From the [Google Chrome accessibility developer tools][chrome]:
```html
<label>
Address:
<input>
</label>
```
[chrome]: https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#controls-and-media-elements-should-have-labels
=> Accept `<label><input></label>`

test-support/helpers/a11y/helpers/actions.js, tests/acceptance/actions-test.js, tests/dummy/app/templates/actions.hbs
Form elements can have [actions triggered by submit][submit]:
```hbs
<form {{action "save" on="submit"}}`>
</form>
```
[submit]: https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/packages/ember-routing-htmlbars/lib/keywords/element-action.js#L51
=> Allow `<form>` elements to have `{{action}}`

test-support/helpers/a11y/helpers/alt-text.js, tests/acceptance/a11y-test-test.js, tests/acceptance/alt-text-test.js, tests/dummy/app/templates/alt-text.hbs
Right now, if you have an empty alt-attribute, an error is thrown:
```html
```
However, elements are actually allowed to have an empty alt-attribute if they are truly decorative:
http://www.w3.org/TR/WCAG20-TECHS/H67.html
Note the difference between having an empty alt-attribute and no alt-attribute at all.
I changed the check from `getAttribute("alt")` to `hasAttribute("alt")`. I also adapted the tests to reflect this behaviour and added a new test for this use case.
=> Do not throw error if alt tag is present but empty

README.md, bower.json, test-support/helpers/a11y/helpers/focusable-visibility.js, test-support/helpers/a11y/register-a11y-helpers.js, tests/acceptance/focusable-visibility-test.js, tests/dummy/app/router.js, tests/dummy/app/templates/focusable-visibility.hbs
Hello again :smile:
In the todo section in the README, the following task was listed: "Verify focusability and visibility (e.g., non-visible elements shouldn't be focusable)". I implemented a new method / helper for this.
A few things of note:
1. This new test helper is a greedy one -  it covers lots of conditions for whether an element is hidden (regardless of whether the browser compensates focus management for you). Before this it matches for a `tabindex` property attached to any element. Can you think of any cases where this might not catch something?
2. Let me know if you feel the logic might be better reversed - that is, grabbing all hidden elements, and making sure there's no `tabindex` assigned. I wrote it this way for cleaner code / use of a greedy selector, but happy to change …
=> Add helper to verify focusability and visibility as a pair

README.md, test-support/helpers/a11y/helpers/alt-text.js, test-support/helpers/a11y/register-a11y-helpers.js, tests/acceptance/a11y-test-test.js, tests/acceptance/alt-text-test.js, tests/dummy/app/templates/alt-text.hbs
Hi! :smile_cat: 
In the todo section in the README, the following task was listed: "Alternative text for other elements (e.g., object, embed)". I looked up the elements where an alt attribute is recommended (rather than a name attribute, etc) and implemented a new method for this.
A few things of note:
1. For backwards compatibility, I've left in the img alt test. But if you'd prefer to just replace this method with my new one and bump this to a major version, let me know.
2. I created new test content for the dummy app to the best of my grokking abilities. 
2. There was a weird jquery version incompatibility issue preventing the tests from running locally or within Travis, so I went ahead and stepped down the version tolerance to solve this temporarily.
Thank you so much! :grin:
=> Check for alt attribute on all non-text elements

README.md, app/instance-initializers/axe-component.js
I like the additional options being enabled for components, but I've found that sometimes it can be useful to A) set app-wide component defaults, and/or B) easily control these app-wide settings on the fly during development.
This led me to making  `ember-a11y-testing` configurable through the app’s ENV hash:
```javascript
ENV['ember-a11y-testing'] = {
componentOptions: {
turnAuditOff: true
...
}
}
};
```
All we’d have to do is have our instance initializer read in the hash from `../config/environment`, and the component properties for `axeOptions`, `axeCallback`, `turnAuditOff` have the opportunity to be set to what’s defined on `ENV['ember-a11y-testing'].componentOptions.` (Side note: I layered in the `componentOptions` property so that -- if we're okay with this approach -- we could …
=> Allow passing component configuration options in environment configuration

content-for/test-body-footer.html, tests/unit/test-body-footer-test.js
Original PR from ember-axe: https://github.com/trentmwillis/ember-axe/pull/7
As we are about to use this add-on in a new application, the other developer and I thought it would be nice to have more descriptive logging in the console rather than sifting through the `violations` object output.
This both updates the default messages that is displayed inside the browser test runner, along with more precise console logging, rather than dumping the entire `violations` object flat out.
=> Add more descriptive violation logging

blueprints/ember-a11y-testing/index.js, bower.json
This PR addresses an inconsistency that I found between the version of `axe-core` that we're using internally in the project, and the one that we're adding to consuming project via the blueprint's `afterInstall` hook. 
Basically, [not specifying a version here](https://github.com/ember-a11y/ember-a11y-testing/compare/master...BrianSipple:update-to-axe-core-1.1.1-and-fix-adding-to-project?expand=1#diff-26407cd03de86c22a240984245d3ab49L7) has the same effect as just running `bower install axe-core`: The latest version is what gets used. 
For consuming apps, there's a bit of serendipity here, because 1.1.1 appears to have improved catching violations in a few ways and using it lead to me noticing the inconsistency in the first place. But in short, 
the current state can be tested by …
=> Update axe-core Dependency and explicitly match it in the afterInstall hook

.travis.yml, bower.json, package.json, tests/.jshintrc, tests/helpers/module-for-acceptance.js, tests/unit/instance-initializers/axe-component-test.js
This PR updates the project to `ember-cli` @ 2.6.2 and makes a few relevant [changes for the new version](https://github.com/ember-cli/ember-cli/releases). 
Mainly...
* Update tests to pass `jshint` after it started finding unused variables.
* Update minor & patch versions of various dependencies in `package.json`
* Update `npm test` command to run `ember try:each`
* Update `.travis.yml` to use the latest `before_install` and `script` settings.
* Remove `ember-try` as a `devDependency` -- it's now included with Ember CLI.
=> Update dependencies and project structure for Ember-CLI 2.6.2

app/instance-initializers/axe-component.js, tests/unit/instance-initializers/axe-component-test.js
I discovered a fun bug with our custom `axeViolationClassNames` functionality:
We’re expecting this to be an Array when we use it in the `axe.a11yCheck` callback, but in the (I think very common) case where someone passes them as a string argument in a component’s template, that’s not quite what happens:
This fix for this is just to make sure we check for `axeViolationClassNames` being a string, and if it is, [split it on whitespace]() to make an array element from each word. 
I also took the opportunity to clean up the tests in general while writing a new one for this issue, so you’ll see a few line changes there as well. (The main change is a helper function that allows each test to not have to stub `axe.a11yCheck` manually.)
=> Fix parsing of custom violation class names

.travis.yml, blueprints/ember-a11y-testing/index.js, node-tests/blueprint-tests.js, package.json
Realized that the `axe-core` version in the blueprint is outdated. Fixed it & added a test to make sure we keep the version in the addon and blueprint in sync.
=> Ensure axe-versions are in sync

.travis.yml, config/ember-try.js
With [Glimmer 2 Alpha builds rolling out](http://emberjs.com/blog/2016/07/29/announcing-the-glimmer-2-alpha.html), there's a good opportunity to start having projects run tests against it in CI. 
This PR adds the proper configuration to ember-try and travis for doing so.
=> add alpha config to ember-try and update travis

addon/utils/violations-helper.js, app/instance-initializers/axe-component.js, app/instance-initializers/violations-helper.js, index.js, tests/acceptance/violations-test.js, tests/unit/instance-initializers/axe-component-test.js, tests/unit/instance-initializers/violations-helper-test.js, tests/unit/utils/violations-helper-test.js
Util object that exposes some helper methods in the console. Hopefully makes dealing with violations in development a little less messy.
As discussed @nathanhammond 
https://github.com/ember-a11y/ember-a11y-testing/issues/18#issuecomment-231880458
=> Expose violationsHelper to global scope.

.travis.yml
Currently, our CI builds are throwing a deprecation warning from `ember-try` about the [test command syntax we're using](https://travis-ci.org/ember-a11y/ember-a11y-testing/jobs/152856315#L257). 
This PR just does a bit of future-proofing, and gets `travis.yml` using the [latest recommended style](https://travis-ci.org/ember-a11y/ember-a11y-testing/jobs/152856315#L259).
=> CI: Update travis test command syntax

.travis.yml, bower.json, config/ember-try.js, content-for/test-body-footer.html, package.json, tests/acceptance/auto-run-test.js, tests/dummy/app/index.html, tests/index.html
Hoping this cuts down on the Travis flakiness.
Previously, the auto-run feature wasn't using a test waiter or test promises, and thus we had no guarantee that the audit actually finished prior to the test run finishing.
=> Upgrade dependencies and improve stability of auto-run

README.md, addon-test-support/audit.js, content-for/test-body-footer.html, tests/acceptance/a11y-audit-test.js, tests/integration/helpers/a11y-audit-test.js
This introduces a test helper, `a11yAudit`, to run the axe-core audit on-demand within tests, instead of relying on the default auto-run or component-reopening.
cc @rwjblue @sarbbottam @ember-a11y/core
=> Add a11y-audit test helper

content-for/test-body-footer.html, tests/acceptance/auto-run-test.js, tests/acceptance/violations-test.js, tests/unit/test-body-footer-test.js
Since axe-core switched to using Promises internally, the exceptions during auto-run were getting swallowed. There is no correct way to hook into the Testing Promise system Ember uses, so we instead simply catch any errors and report them through the test adapter.
This will fix https://github.com/ember-a11y/ember-a11y-testing/issues/47.
=> Properly report exceptions

index.js
Fixes #61. Verified by linking locally against the reproduction repo.
This was introduced when moving `axe-core` to `npm` (#58).
cc @abought
=> Include axe-core in all non-prod environments

README.md, app/instance-initializers/axe-component.js
Addressing https://github.com/ember-a11y/ember-a11y-testing/issues/51.
@BrianSipple would appreciate your review since you implemented the original feature.
@ember-a11y/core, if any of you have objections, let me know.
=> Allow turnAuditOff to be defined globally

index.js
This bit me in a recent 2.12 upgrade, so I'm making sure other addons have the call right
=> Ensure `super` call is bounded

addon-test-support/audit-if.js, addon-test-support/utils.js, tests/integration/helpers/a11y-audit-if-test.js
Added `a11yAuditIf` method to run `a11yAudit` if `enableA11yAudit=true` is passed as `--query`.
---
**Context**
We want to setup a11y audit as a nightly offline process and don't want to disrupt the current CI/CD pipeline. Since the code changes to accommodate the a11y audit is done in the same repository, we wanted to have a controlled method.
So for the regular acceptance test run `a11yAuditIf()` will function as a `noop` since `--query=enableA11yAudit=true` will not be available.
However for, the dedicated nightly build due to the presence of `--query=enableA11yAudit=true` as part of the test command a11y audit will be performed.
=> feat(a11yAudit): opt in to a11yAudit

index.js
This stops the style blocks from getting added to the html files on production builds. Can we publish a patch release on merging this?
=> Don't include content for production builds

addon/utils/violations-helper.js, app/instance-initializers/axe-component.js, tests/acceptance/violations-test.js, tests/dummy/config/environment.js, tests/integration/instance-initializers/axe-component-test.js
Addresses issue #18 
* Console logging is  formatted as ` [impact]: [help]. Offending markup is: [nodes.html]`
* Ex: `critical: Form elements must have labels. Offending markup is: <input id="test" type="test">`
=> Present information in an easy-to-digest format #18

package.json
- Enforcing installation of axe-core 2.4.2 or greater due to security issues.
- Locked ember-cli-htmlbars-inline-precompile to 0.3.11. Versions greater than 0.3.11 (0.3.12 and 0.3.13) are causing template compilation to fail (hence all pull requests since last updates were failing).
@trentmwillis
=> Package upgrades and locking version of htmlbars-inline-precompile.

addon-test-support/audit.js, addon/utils/format-violation.js, addon/utils/violations-helper.js, app/instance-initializers/axe-component.js, app/instance-initializers/violations-helper.js, package-lock.json, tests/acceptance/a11y-audit-test.js, tests/acceptance/violations-test.js, tests/integration/helpers/a11y-audit-if-test.js, tests/integration/helpers/a11y-audit-test.js, tests/integration/instance-initializers/axe-component-test.js, tests/unit/utils/format-violation-test.js, tests/unit/utils/violations-helper-test.js
This PR extracts the violation formatting logic into a util class that can be used in both component audit and test audit scenarios.
It also changes the violationsHelper so that it works more like a singleton and is used throughout the project as a module instead of a global. It's still exposed as a global in the initializer, though. This also makes it work properly in test mode.
---
Here's a before/after of using ember-a11y-testing in another project's test suite:
Before:
After:
---
Here's a screenshot of development mode to show that it still works fine:
=> Improve logging of violations in test mode

.travis.yml, addon/services/concurrent-axe.js, app/instance-initializers/axe-component.js, app/services/concurrent-axe.js, package.json, tests/acceptance/a11y-audit-test.js, tests/dummy/app/components/x-text-input.js, tests/dummy/app/templates/components/x-text-input.hbs, tests/dummy/app/templates/violations.hbs, tests/integration/instance-initializers/axe-component-test.js, tests/unit/services/concurrent-axe-test.js, yarn.lock
There have been quite a number of axe-core updates since v2.6.1, including numerous bug fixes, additional rules and rule updates, and performance optimizations. As such, it is imperative that an organization getting started with accessibility testing is able to take advantage of new features provided in the latest release of axe-core.
This pull request facilitates the axe-core version upgrade to 3.1.2. Axe-component.js has been updated to use the newer axe.run API method (a11yCheck has been deprecated), and updated the callback function signature (first argument is now an error object, second argument is the audit result). Related tests have also be updated to reflect these changes.
One particular aspect to take note related to axe-core v3, is that concurrent axe calls, such as those that …
=> Axe-core v3.1.2 update

addon/utils/concurrent-axe.js, app/instance-initializers/axe-component.js, app/services/concurrent-axe.js, index.js, tests/unit/utils/concurrent-axe-test.js
Using a [service](https://github.com/ember-a11y/ember-a11y-testing/blob/master/addon/services/concurrent-axe.js) to mitigate the [aXe concurrency issue](https://github.com/ember-a11y/ember-a11y-testing/blob/master/addon/services/concurrent-axe.js) proved to be problematic for apps utilizing Ember engines, as the service needs to be explicitly defined as a dependency for each engine. This a bit too much overhead, especially for apps that don't utilize the visual component audit feature. As a fix, I have changed the service to a simple class, as there's no stateful information being stored in the service anyway. This is a much cleaner approach and removes the overhead of explicit dependency declarations.
We've also encountered a use case where we need to exclude axe-core from development …
=> Fix services for engines, add option to exclude axe-core for visual component audit feature

app/instance-initializers/axe-component.js
Provides empty object if axeOptions are not defined to prevent axe.run from failing. Prior versions of axe worked with undefined options argument, while v3 explicitly expects an object. Resolves the issue by adding empty object default.
=> Fixes #113

addon-test-support/audit.js, addon-test-support/utils.js
We'd like to add some simple user timing markers to get a better idea of a11y testing perf impacts on acceptance test suites.
=> Adds user timing mechanism for performance profiling

app/instance-initializers/axe-component.js, package.json, yarn.lock
Bumping axe-core to latest release, which has improved performance to speed up a11y audits. Also including a comment for visual audit instance initializer based on discussions with @stefanpenner.
=> Axe-core version bump to 3.2.1

addon-test-support/audit.js, addon/instance-initializers/axe-component.js, addon/utils/violations-helper.js, tests/integration/instance-initializers/axe-component-test.js, tests/unit/instance-initializers/violations-helper-test.js, tests/unit/utils/concurrent-axe-test.js, tests/unit/utils/violations-helper-test.js
Removes usage of soon to be deprecated Ember.Logger. Also fixes Sinon.js deprecation warnings by replacing all sinon.sandbox.create() calls. Additionally includes some minor cleanup of a couple tests.
I initially created a utility conditional wrapper around console calls, but found such a thing to be pretty tricky to test reliably. Even though this addon supports Ember 2.x, after giving it some thought, I don't see a good reason why folks would be doing dev work or running tests with something like IE 10, especially given that this is a dev-only addon and does not make it to production code.
=> Fixes #127

addon-test-support/audit.js, addon/utils/concurrent-axe.js, tests/acceptance/a11y-audit-test.js, tests/dummy/app/index.html, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/components/violations-grid-item.hbs, tests/dummy/app/templates/violations.hbs, tests/index.html
Adds fix by checking for include and/or exclude properties. Adds test to verify correct behavior.
=> Fixes #124. Allows a11yAudit to account for axe include/exclude context param.

addon/instance-initializers/axe-component.js, index.js
Adds override to exclude all addon related code from production builds.
Makes axe check a bit more defensive.
- We recently ran into an issue where the axe-component initializer was getting bundled with a bunch of engines, causing exceptions by calling axe where it didn't exist. Although this was ultimately a build issue not related to the addon, the failure can definitely be made much more graceful.
=> Fixes code included in production builds [#108]

.travis.yml, package.json
The Travis CI build is currently broken due to a transient dependency that no longer supports Node v8. I'm bumping minimum support to v10 as v8 became EOL in January. This also matches the current support level for Ember CLI. Also fixed Travis config validation warnings.
=> Fix build issues due to Node.js v8 EOL

tests/dummy/config/environment.js
Build fails due to deprecated `radiogroup` rule.
=> Fixes axe-core v4.0.1 build

yarn.lock
The current lockfile in master contained transitive deps that were using an older version of fsevents, causing `yarn install` to fail on a fresh checkout. This change regenerates the lockfile fresh, which allows us to ensure the dependencies are correctly expressed in `yarn.lock`.
=> Regenerates lockfile to address issue with fsevents version

RELEASE.md, package.json, yarn.lock
This the result of running `npx create-rwjblue-release-it-setup --update`.
After this change, we should change our process to:
* Ensure that each pull request that is merged has the appropriate label (bug, enhancement, internal, documentation, etc).
* Update pull request titles to be a good changelog entry (tweaking the verbiage and whatnot to be more "customer" oriented)
* Ensure that the prerequisites listed in `RELEASE.md` are satisified (primarily a `GITHUB_AUTH` environment variable)
* Use `npx release-it` for the actual release process itself
=> Setup automated release system.

addon-test-support/audit-if.ts, addon-test-support/audit.ts, tests/unit/audit-test.ts
This PR prepares for the potential of deprecating the `a11yAuditIf` helper. This helper can be merged into `a11yAudit` by allowing it to accept another optional parameter: URL. This allows for two things:
1. The aforementioned deprecation of an extra, largely unnecessary API (simplification)
2. The removal of the `getLocation` function, which returns `window.location` and exists only to provide a stubbing mechanism for the `getUrlParameter` function. By adding an extra URL param to `a11yAudit`, we can simply test that function by passing in the required value, and provide the default as `window.location`.
⚠️ This change also includes a breaking change that removes support for older test infra versions (folks using the long deprecated `moduleForAcceptance` test system) by removing …
=> Refactors param normalization in `a11yAudit`

addon-test-support/audit.ts, tests/acceptance/a11y-audit-test.js, tests/integration/helpers/a11y-audit-if-test.js, tests/integration/helpers/a11y-audit-test.js
This addon was leveraging Ember's `assert` function to trigger failures. This PR removes that in favor of plain `Error` objects (which is ultimately what `assert` uses under the hood.
=> Converts the `Ember.assert` usage to throwing error for failing tests

addon/utils/format-violation.ts, addon/utils/violations-helper.ts
Converts
- addon/utils/format-violation.js
- addon/utils/violations-helper.js
to TS to avoid issue with compile-time errors due to JS imported into TS.
=> Converting utils to TS to fix compile time errors

addon-test-support/audit.ts, addon-test-support/index.ts, addon-test-support/reporter.ts, addon-test-support/types/index.ts, tests/acceptance/reporter-test.ts
As part of #207, this PR adds a new reporter system that will allow us to provide custom reporting for accessibility violations for test runs.
The reporter conforms to the following interface:
```ts
interface A11yAuditReporter {
(axeResults: AxeResults): Promise<void>;
}
```
A `setCustomReporter` is provided, allowing you to provide a custom `A11yAuditReporter` implementation.
```ts
export function setCustomReporter(
customReporter: A11yAuditReporter = DEFAULT_REPORTER
): void;
```
This API provides the flexibility to shape the violations in any format you want.
=> Adds custom reporter capability

.eslintrc.js, .github/workflows/ci-build.yml, .npmignore, addon-test-support/index.ts, addon-test-support/setup-middleware-reporter.ts, index.js, node-tests/fixtures/violations.json, node-tests/setup-middleware-test.js, package.json, setup-middleware.js, tests/acceptance/setup-middleware-reporter-test.ts, tests/fixtures/violations.json, types/@ember/test-helpers.d.ts, yarn.lock
Adds support for combining the custom reporter with custom middleware, which allows for serializing the results to JSON.
```js
// tests/test-helper.js
import { setupMiddlewareReporter } from 'ember-a11y-testing';
// ...
setupMiddlewareReporter();
// ...
```
This will setup a custom reporter, which gathers the test module name, test name, and violations for each failed audit. Once the suite is done, these results are posted to the testem middleware, ultimately serializing the results to disc.
TODO:
=> Adding ability to post violations via middleware

addon-test-support/index.ts, addon-test-support/logger.ts, addon-test-support/reporter.ts, addon-test-support/setup-console-logger.ts, tests/test-helper.js
Recent refactors removed the feature that output failures to the console. This PR restores that, using a slightly nicer format inspired by https://github.com/dequelabs/react-axe. 
[An issue](https://github.com/dequelabs/react-axe/issues/180) has been opened on that repository which proposes extracting the formatting functionality to a separate repo, in order to reduce duplication.
Example:
=> Adding enhanced console logging

package.json, yarn.lock
Using `ember-cli-typescript@4.0.0` results in the typescript files not being correctly transpiled when using embroider. This PR downgrades the version to `3.0.0`. 
Issue: https://github.com/embroider-build/embroider/issues/528
=> Downgrading ember-cli-typescript to 3.0.0 for embroider compatability

addon-test-support/index.ts, addon-test-support/setup-middleware-reporter.ts, setup-middleware.js, tests/acceptance/setup-middleware-reporter-test.ts
The results that are returned from each failed audit are quite large. When considering the size of the payloads passed through the middleware, passing raw `AxeResults` objects could result in a very large payload. This PR specifically reduces the size of the overall payload that's sent through the middleware, which will also reduce the size written to disc.
In addition to this, there's extra data that's useful to gather when assessing audits, such as
1. routes visited
2. urls visited
The stored result, per test, adheres to this interface:
```ts
interface AxeTestResult {
moduleName: string;
testName: string;
urls: string[];
routes: string[];
helpers: string[];
stack: string;
violations: Result[];
}
```
<details>
<summary>JSON result example</summary>
```json
[
{
"moduleName": …
```
=> Updating result schema to include more specific data

index.js, package.json, yarn.lock
Uses new `validate-peer-dependencies` package over `ember-cli-version-checker`.
=> Adding validate-peer-dependencies over version checker

.github/workflows/ci-build.yml, config/ember-try.js, ember-cli-build.js, index.js, package.json, tests/dummy/config/targets.js, yarn.lock
When parent applications are using ember-qunit > 5 this causes an invalid lookup for qunit in requirejs because ember-qunit no longer provides the AMD shim for qunit and instead uses ember-auto-import. This change conditionally uses ember-auto-import if that shim is present or not along with adding test cases for general embroider compatibility.
Related issue: https://github.com/ember-cli/ember-exam/issues/634
=> Fix cannot find module `qunit` under embroider

content-for/test-head-footer.html, package.json, yarn.lock
Related to PRs https://github.com/ember-a11y/ember-a11y-testing/pull/234 and https://github.com/emberjs/ember-qunit/pull/817.
Now that the ember testing container issues have been resolved, it is no longer necessary to pin `ember-qunit` to v5.0.0. I've taken this opportunity to also bump `axe-core` to the latest version (4.1.2) and fix the a11y related container CSS styles so that test results are consistent between standard and fullscreen modes. (I'm not entirely sure how these were even working properly before with the `static` CSS positioning.)
Verified all tests pass and no regressions have been introduced by running these changes through several apps that are actively using the addon.
=> Unpin ember-qunit, fix testing container CSS overrides

README.md
setRunOptions is imported from /test-support, not the root
=> Correct import path of setRunOptions in README

README.md
It's currently not clear from the docs that when using `setupGlobalA11yHooks`, you also need to ensure you're using the `enableA11yAudit` query param in addition to an invocation strategy to ensure the hooks will run. This PR adds this information to the docs.
[Rendered](https://github.com/ember-a11y/ember-a11y-testing/blob/update-readme-global-setup/README.md)
=> Updating README to indicate the need to use query param with global setup helper

README.md
Updates the URL to the axe-core API docs.  The previous link, while it properly redirected the path, brought you to the top of the page (the element id linked by the hash must have changed at some point)
=> Correct link to axe-core API docs

index.js, package.json, renovate.json, vendor/shims/axe-core.js, yarn.lock
should fix #248
- checked with @ef4 & the lines removed are per his recommendation (as the author of `ember-auto-import`) - seems we were doing some redundant things that `ember-auto-import` was already providing. 
- updates the version of `ember-qunit`
I did notice that some of the dummy app tests are failing. Perhaps we should plan to revisit the app and update it. I'll make a new issue for that.
=> Removes unnecessary, legacy build code for inclusion of axe dependencies.

addon-test-support/logger.ts
printResults checks if testSuiteResults exists before printing to the console.
Currently printing `Axe issues` when there aren't any is confusing and adds noise.
=> Don't print to the console when there are no issues

addon-test-support/format-violation.ts, tests/unit/format-violation-test.ts
It's possible when encountering violations that the violations' node array is empty. In that case, when we try to format the violation, we output a 0 count for violations due to the fact we try to infer the violations count occurrences through the presence of node's html.
In addition, the `formatViolation` tests were not indicative of the actual execution of this function. The function signature indicated that both violation and markup could be either undefined or optional respectively, but this did not reflect how this was used in practice. The two parameters are always required, and this misalignment helped manifest this bug.
This PR addresses both fixing the issue, and updating the tests to better reflect the usage.
=> Fixes issue when violations count is reported to be 0

README.md
`axe.run` accepts different options from `axe.configure`. This PR modifies documentation to note that the options passed to ember-a11y-testing are for `axe.run`, and removes an invalid `checks` property that is potentially misleading.
See: https://github.com/dequelabs/axe-core/commit/12767735015a082f46ecb066f018a4203c6d48c7
Also wondering, would it be possible to expose a way to pass options to `axe.configure`?
=> Documentation: Clarify that options are for axe.run, remove invalid `checks` property

README.md, setup-middleware.js
Current invocations of the middleware reporter cause the deletion of all prior reports from the `ember-a11y-report` directory. This behavior is undesirable as it causes an unexpected removal of prior logs, which may lead to a loss of data if the reports aren't backed up. It also makes it difficult to use with test executions that are spread across multiple partitions, in that only the reports from the last partition get archived. This change removes file deletion so that subsequent reports are additive and includes documentation about the change in behavior.
I think this update merits some discussion on whether it constitutes a major version upgrade. While it isn't necessarily a breaking change, there may be some consumers that depend on auto file deletion and will be unaware that it's …
=> Prevent deletion of a11y audit reports

addon-test-support/audit-if.ts, types/ember-debug.d.ts
Fixes the current usages of deprecate to include `for` and `since`. This will ensure CI passes on canary.
=> Fixes deprecate call to include for and since props

package.json, yarn.lock
There do not seem to be changes relevant for this addon, so both 2.x and 3.x should be fine:
https://github.com/emberjs/ember-test-waiters/releases/tag/v3.0.0
I also had to update ember-cli-typescript to 4.x, otherwise the embroider build complained (for whatever reason). But as far as I see 4.x also has no relevant changes for this addon: https://github.com/typed-ember/ember-cli-typescript/releases/tag/v4.0.0
=> Allow @ember/test-waiters 3.x

node-tests/setup-middleware-test.js, package.json, yarn.lock
The port for the middleware tests was hardcoded, and when running them locally this port was in use. This caused the tests to fail, and it forced me to debug locally to determine the cause. 
Adding automated port discovery will alleviate this.
=> Adds get-port to ensure we have an available port

README.md, package.json
#325 requires major release, so good time to drop old Node.js version support.
=> Drop Node.js 10 support

.npmignore
these files don't used in runtime so no needed in npm
=> Add `docs` folder and `RELEASE.md` file to npmignore

package.json, yarn.lock
The underlying regression in v2.5.0 was fixed, see https://github.com/krisk/Fuse/issues/600
=> Remove `fuse.js` resolution from package.json

package.json, yarn.lock
This change addresses various CI failures so that a new release can eventually be published which includes the latest version of axe-core. The specific updates include the following:
* Bumps Node in the Volta config to address a Node incompatibility error from a transient dependency.
* Pins DF TS types for `@ember/test-helpers`. Due to recent changes in the way the DF types are setup, this project's custom types end up clobbering `@ember/test-helpers`'s types.
* Upgrades `ember-cli-babel` and its transient deps to fix build errors in the `try-each` scenarios.
=> Fixes CI failures

addon-test-support/setup-middleware-reporter.ts, tests/unit/get-current-route-name-test.ts
Fixes issue #489.
The recent release of `@ember/test-helpers` v2.9.0 added an [assertion error](https://github.com/emberjs/ember-test-helpers/blob/ded104ba04e354bfefca4d0b4d2079eb70f29814/addon-test-support/%40ember/test-helpers/setup-application-context.ts#L200) that is emitted if the route name isn't available for a particular test. This results in a slew of unrelated application test failures when running the middleware reporter.
The resulting test failures typically consist of:
```sh
Promise rejected during "clicking the View Permissions button brings up the View modal": Assertion Failed: currentRouteName shoudl be a string"Source:
Error: Assertion Failed: currentRouteName shoudl be a string
at assert (http://localhost:4444/talent/assets/vendor-static.js:32729:15)
at currentRouteName …
```
=> Fixes currentRouteName middleware reporter test failures

.github/workflows/ci.yml, README.md, addon-test-support/setup-global-a11y-hooks.ts, config/ember-try.js, package.json, yarn.lock
depends upon https://github.com/ember-a11y/ember-a11y-testing/pull/508
partially resolves #506 
- Upgrades `@ember/test-helpers` to `^3.x`.
- Drops support for Node.js < 16.x. These versions are no longer supported by `@ember/test-helpers`. https://github.com/emberjs/ember-test-helpers/blob/92392b110565de201729037b8469362dea1bb472/addon/package.json#L106
- Drop support for Ember < 4
=> Upgrade @ember/test-helpers to 3.x

content-for/test-head-footer.html
Copying the proposal that is added in #505 
With animations and transitions in place, the a11y tests can non-deterministically fail.
For eg., lets say we have a disabled button and on certain action (click of another button) we enable the button. Lets say we have a transition property set on the button to transition the background-color of the button.
Now, lets say the disabled button contrast ratio doesn't meet the AA guidelines. The a11y tests will continue to pass since the axe-core doesn't run the tests on disabled elements. In the example that i mentioned above, when the axe-core tests run as soon as the button gets enabled, it can lead to a11y violation error since the background transition might not have completed yet.
In this PR, we are disabling animation and transition so that …
=> Disabling transitions and animations while running axe tests

addon-test-support/setup-middleware-reporter.ts
* Fixes issue #513.
In some circumstances, when using the middleware reporter, the a11y audit completes after test context has been torn down, resulting in test failures due to the thrown errors from using `currentURL` and `currentRouteName`. The fix ensures `context` exists before these two methods are called.
* Local tests pass.
* Manually validated tests are no longer failing from within the context of a host app.
=> Ensures context for current URL & route middleware reporting

package.json
v4 of `@ember/test-helpers` was released lately, and appears to work just fine with `ember-a11y-testing` since the breaking changes in that release are irrelevant to this addon :)
/cc @drewlee @MelSumner
=> Widen `@ember/test-helpers` peer dependency declaration

addon-test-support/index.ts, addon-test-support/reporter.ts
We currently expose `_TEST_SUITE_RESULTS` and `_middlewareReporter` to allow customizing reporting without needing to build the entire set of reporting / middleware / test violation capture. But we don't currently allow wrapping the default reporter which hampers any ability to filter violation results (or report on them differently) while still using the core setup within default reporter.
It's probably worth thinking through ways to expose all of these items as "wrappable" more easily, but short-term I'm working on an app that could use the ability to filter results in certain scenarios
=> Allow wrapping the default reporter without having to rebuild it

README.md, addon-test-support/index.ts, addon-test-support/setup-qunit.ts
You can setup a new configuration checkbox in QUnit and Testem by using the `setupQUnitA11yAudit`
When the checkbox is checked, it will set `enableA11yAudit` as a query param.
To use, import and invoke the setup function, passing in your QUnit instance:
```js
// tests/test-helper.js
import Application from 'my-app/app';
import config from 'my-app/config/environment';
import * as QUnit from 'qunit';
import { setApplication } from '@ember/test-helpers';
import { start } from 'ember-qunit';
import { setupGlobalA11yHooks, setupQUnitA11yAudit } from 'ember-a11y-testing/test-support';
setApplication(Application.create(config.APP));
setupGlobalA11yHooks(() => true);
setupQUnitA11yAudit(QUnit);
start();
```
----
Here is the result in Testem:
=> feat: add qunit config

tests/integration/helpers/a11y-audit-test.ts
following the guides here: https://guides.emberjs.com/v5.7.0/typescript/application-development/testing/
This restores the needed `Element` to the TestContext, allowing Typescript checks to pass successfully
=> fix typescript context for integration tests

addon-test-support/audit.ts, addon-test-support/logger.ts, addon-test-support/performance.ts, addon-test-support/reporter.ts, addon-test-support/run-options.ts, addon-test-support/setup-global-a11y-hooks.ts, addon-test-support/setup-middleware-reporter.ts
I was seeing some errors about types from this add-on when running types in a client app using `verbatimModuleSyntax: true`. Could likely clean that up locally but figured I'd send these updates in so we all benefit. This doesn't change functionality, just ensures that we do type-only imports so we don't end up with larger bundle sizes by mistake
=> Tighten type imports

package.json, yarn.lock
The body-parser dependency was added in https://github.com/ember-a11y/ember-a11y-testing/commit/cf0d1227c047725d3682101d3c6469145c8a3fdb#diff-2b7b86d547afb814ffca762b5a1162f99ed0f3fbf12e23bd59ed82343d6270e4 but later moved into Steve's `@scalvert/ember-setup-middleware-reporter` add-on. As such, we don't need to keep it up-to-date here
=> Remove unused body-parser dependency

package.json, tsconfig.json, yarn.lock
Per the readme at https://github.com/ember-polyfills/ember-destroyable-polyfill the polyfill is inert after Ember 3.22 Seeing as we now support Ember 4+ only, we can take this out
=> Drop ember-destroyable-polyfill that is no longer needed
