ember-a11y/ember-a11y-testing

bower.json
We've published a new version to npm and bower. Tests are passing. Let me know if you run into any issues!
=> Update to axe-core 2.0.5

.travis.yml, app/instance-initializers/axe-component.js, app/instance-initializers/violations-helper.js, bower.json, config/ember-try.js, tests/acceptance/violations-test.js, tests/integration/instance-initializers/axe-component-test.js
This should hopefully get CI green at which point we'll be able to land other PRs.
=> Fix Travis and improve overall test stability

blueprints/ember-a11y-testing/index.js, bower.json
updated axe-core dependency to 2.1.7 (current version)
=> update to axe-core

tests/integration/instance-initializers/axe-component-test.js
Fixes https://github.com/ember-a11y/ember-a11y-testing/issues/69.
=> Fix axe-component error test

README.md, addon-test-support/audit.js, tests/acceptance/a11y-audit-test.js, tests/integration/helpers/a11y-audit-test.js
=> Support passing options as a single argument to a11yAudit

package.json
=> Update axe-core version and range

README.md
This was something that took me a few try-and-error cycles to get right, as the docs in `axe-core` are not very clear on the subject. Perhaps others find it useful.
=> Add example on Readme to disable specific checks

README.md
update README.md - include example code for disabling the scroll option for the color contrast check - (#77)
=> README - example to disable color contrast scroll

.bowerrc, bower.json, package.json
=> Remove bower

README.md
The readme was a little confusing for me to follow. I updated the structure a little bit to make axe options and scoped auditing clearer.
=> Clarify axe options and scoped auditing

README.md, package-lock.json
Updated the links for the axe core API docs and the version number for the rule definitions (so it matches the version we're using in the addon).
=> updating README to fix incorrect links

index.js
This is to fix the build for PR #151.
=> Fix build for ember-cli-version-checker v5

renovate.json
Here we go again...
I believe this will fix our issue 🤞
=> Attempting to fix renovate so it won't open pin dependency PRs

package.json
Output from `npx git-authors-cli`
=> Adding contributors to package.json

package.json, yarn.lock
=> Upgrading @ember/test-helpers to 2.0.0

addon-test-support/audit.ts, package.json, yarn.lock
=> Moves to using promise-based API for axe invocation

ember-cli-build.js, tests/dummy/config/optional-features.json
- sets jquery optional feature to false
- fixes crypto issue
=> Fixes failing CI and crypto error

package.json, yarn.lock
ref https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md#434-2021-10-22
And 
https://github.com/dequelabs/axe-core/pull/3124
https://github.com/dequelabs/axe-core/issues/3082
=> Bump axe-core 4.3.5

config/ember-try.js, package.json, yarn.lock
There is bunch of wins, greatly summarized by @buschtoens in https://twitter.com/buschtoens/status/1449745394594889734
=> Bump ember-auto-import to 2.2.4 and introduce webpack

.eslintrc.js, package.json, tests/acceptance/reporter-test.ts, tests/acceptance/setup-global-a11y-hooks-test.ts, tests/integration/components/setup-global-a11y-hooks-for-render-test.ts, tests/unit/audit-test.ts, tests/unit/calculate-updated-href-test.ts, tests/unit/format-violation-test.ts, yarn.lock
Extracted from #341 to simplify review
=> Introduce `eslint-plugin-qunit` per latest addon blueprint

package.json
Updates contributor email from company account to personal.
=> Updates Andrew Lee's contributor email

addon-test-support/setup-middleware-reporter.ts
This affects folks using `setupMiddlewareReporter`.
Sometimes, like in CI environments, there can exist a race condition where Testem closes before the local middleware reporter can finish writing the reports to the filesystem.
According to [Testem's README][1], it appears the proper way to do this is to use `Testem.afterTests` to send reports. This will keep testem open and prevent the process from exiting before the reports are written.
This seems to be a [known issue with Testem's QUnit integration][2].
[1]: https://github.com/testem/testem/blob/0bd05cec7f83bfe9f2e10ddfab54556d724ee179/README.md#running-browser-code-after-tests-complete
[2]: https://github.com/testem/testem/issues/1577
=> bugfix: prefer using Testem.afterTests instead of QUnit.done

package.json, yarn.lock
Similar to https://github.com/ember-a11y/ember-a11y-testing/pull/580
=> Expand @ember/test-waiters dependency range to allow v4

.github/workflows/ci.yml, config/ember-try.js, package.json, pnpm-lock.yaml, tests/dummy/app/styles/app.scss, tests/dummy/app/styles/components/_button.scss, tests/dummy/app/styles/components/_components.scss, tests/dummy/app/styles/components/_menu-link-item.scss, tests/dummy/app/styles/components/_radio-track.scss, tests/dummy/app/styles/components/_violations-grid-item.scss, tests/dummy/app/styles/globals.scss, tests/dummy/app/styles/object-patterns/_content-box.scss, tests/dummy/app/styles/object-patterns/_object-patterns.scss, tests/dummy/app/styles/pages/_pages.scss, tests/dummy/app/styles/pages/_violations.scss, tests/dummy/app/styles/typography/_headings.scss, tests/dummy/app/styles/typography/_typography.scss, tests/dummy/app/styles/variables/_variables.scss
If merged, this PR: 
- updates the package description
- updates the version of axe-core to v.4.10.3
- updates the try scenarios (and github ci) to test starting with LTS 4.8 and 4.12 (dropping 4.4)
- fixes the sass warnings (move from `import` to `use`)
=> [internal] tidy up
